### ISSUE TITLE
Reuso de material

### ISSUE THREAD

**Issue by leomiquelutti** [salvianoleao/IntroducaoJupyter#2]
Olá Salviano, tudo bem?

Sou professor de geofísica na Uff (Niterói), e gostaria de saber se poderia utilizar, por favor, parte do seu material para aulas na pós-graduação. Claro, dando o devido crédito.

**Comment by salvianoleao** [comment]
Olá prof. Leonardo

Pode usar sim.

                     Salviano A. Leão


Em qua., 10 de mar. de 2021 às 11:47, Leonardo Miquelutti <
notifications@github.com> escreveu:

**Comment by salvianoleao** [comment]
Boa noite Leonardo

Se você achar que vale a pena, eu construi uma imagem docker
para usar no meu curso, na qual tenho instalei uma série de aplicativos.
As instruções de uso seguem em anexo

Abraços
                     Salviano A. Leão


Em qua., 10 de mar. de 2021 às 11:47, Leonardo Miquelutti <
notifications@github.com> escreveu:

**Comment by leomiquelutti** [comment]
Olá Salviano,

muitíssimo obrigado! Quanto ao docker, não precisarei, pois preciso apenas da aula introdutória acerca do Jupyter - muito boa, diga-se de passagem. Bem completa! Mas desenvolverei a disciplina com o Google Colab, e não com notebooks locais dos alunos.
